apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mytestapp
  name: mytestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mytestapp
  template:
    metadata:
      labels:
        app: mytestapp
    spec:
      containers:
      - image: nginx
        name: "{{ .Values.image.repository }}:{{ .Values.image.tag  }}"
        env:
        - name: SPRING_POSTGRES_USERNAME 
          value: "myapplication"
        - name: SPRING_POSTGRES_PASSWORD
          value: "M3P@ssw0rd!"
        - name: SPRING_POSTGRES_URL 
          value: "my-db-test.io"



