apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: mytestapp-vs 
spec:
  hosts:
  - "*"
  gateways:
  - mytestapp-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: myservice 
        port:
          number: 80
